export const ERROR_CODES = Object.freeze({
  "BAD REQUEST": 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  "NOT FOUND": 404,
  "METHOD NOT ALLOWED": 405,
  "NOT ACCEPTABLE": 406,
  "PROXY AUTHENTICATION REQUIRED": 407,
  "REQUEST TIMEOUT": 408,
  CONFLICT: 409,
  GONE: 410,
  "LENGTH REQUIRED": 411,
  "PRECONDITION FAILED": 412,
  "PAYLOAD TOO LARGE": 413,
  "URI TOO LONG": 414,
});

export const SERVER_ERROR = Object.freeze({
  "INTERNAL SERVER ERROR": 500,
});

export const SUCCESS_CODES = Object.freeze({
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  "NON-AUTHORITATIVE INFORMATION": 203,
  "NO CONTENT": 204,
  "RESET CONTENT": 205,
  "PARTIAL CONTENT": 206,
  "MULTI-STATUS": 207,
});
